### ISSUE TITLE
你好！GREAT work，想问问您是如何添加英文翻译的？

### ISSUE THREAD

**Issue by Demian101** [r12f/sonic-book#19]
如题

我现在使用的是 https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/USAGE.md
+ https://github.com/mgeisler/cloud-translate

但是 cloud-translate 我遇到了一个问题，其 Source_lang 默认是 English，我不知道如何修改 lol

**Comment by r12f** [comment]
谢谢谢谢！我自己写了一个小工具叫做potr：https://github.com/r12f/potr，翻译引擎用的是deepl和azure openai的gpt 3.5 （gpt4 waiting list刚过，还没来得及试），可以试一试看看能不能满足你的需要～

google的引擎我还没有支持，不过确实可以考虑也加上～

**Comment by r12f** [comment]
no extra work needed here. closed.
